#!/usr/bin/env node
// Reads *-source.js files and writes corresponding *-script.ts files with the content as an exported string.
// Run automatically via `npm run build` before tsc.

const fs = require('fs');
const path = require('path');

const bridgeDir = path.join(__dirname, '../src/bridge');

const entries = [
  { src: 'injector-source.js',    out: 'injector-script.ts',    export: 'BRIDGE_INJECTOR_SCRIPT' },
  { src: 'storage-source.js',     out: 'storage-script.ts',     export: 'STORAGE_BRIDGE_SCRIPT'  },
  { src: 'network-mock-source.js', out: 'network-mock-script.ts', export: 'NETWORK_MOCK_SCRIPT'   },
  { src: 'clock-source.js',       out: 'clock-script.ts',       export: 'CLOCK_SCRIPT'           },
];

for (const entry of entries) {
  const js = fs.readFileSync(path.join(bridgeDir, entry.src), 'utf-8');
  const escaped = js.replace(/\\/g, '\\\\').replace(/`/g, '\\`').replace(/\$\{/g, '\\${');
  fs.writeFileSync(
    path.join(bridgeDir, entry.out),
    `// Generated by scripts/embed-bridge.js — do not edit directly.\n// Edit src/bridge/${entry.src} instead, then run \`npm run build\`.\nexport const ${entry.export} = \`${escaped}\`;\n`,
  );
  console.log(`embed-bridge: wrote ${entry.out}`);
}
