#!/usr/bin/env node
// Reads injector-source.js and writes injector-script.ts with the content as an exported string.
// Run automatically via `npm run build` before tsc.

const fs = require('fs');
const path = require('path');

const src = path.join(__dirname, '../src/bridge/injector-source.js');
const out = path.join(__dirname, '../src/bridge/injector-script.ts');

const js = fs.readFileSync(src, 'utf-8');
const escaped = js.replace(/\\/g, '\\\\').replace(/`/g, '\\`').replace(/\$\{/g, '\\${');

fs.writeFileSync(
  out,
  `// Generated by scripts/embed-bridge.js — do not edit directly.\n// Edit src/bridge/injector-source.js instead, then run \`npm run build\`.\nexport const BRIDGE_INJECTOR_SCRIPT = \`${escaped}\`;\n`,
);

console.log('embed-bridge: wrote injector-script.ts');
